// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZceJoodOf2xRpIDWEC78OXyzE82PZwy8',
    appId: '1:916281932211:web:54e846e770edc46b66b3c6',
    messagingSenderId: '916281932211',
    projectId: 'khazanah-49252',
    authDomain: 'khazanah-49252.firebaseapp.com',
    storageBucket: 'khazanah-49252.firebasestorage.app',
    measurementId: 'G-MQHS134QNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArlw3E297RTN83hwjiwlFj6plcwUY1T-Q',
    appId: '1:916281932211:android:30b6f4874e744a3166b3c6',
    messagingSenderId: '916281932211',
    projectId: 'khazanah-49252',
    storageBucket: 'khazanah-49252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgxB2LGygy_JGyldgomRmazm4D-Nujs3c',
    appId: '1:916281932211:ios:bda08b1b13ef471a66b3c6',
    messagingSenderId: '916281932211',
    projectId: 'khazanah-49252',
    storageBucket: 'khazanah-49252.firebasestorage.app',
    iosBundleId: 'com.khazanah.khazanah',
  );
}